# Generated by Django 4.1 on 2023-12-02 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_login',
        ),
    ]
