# Generated by Django 4.1 on 2023-12-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0004_remove_user_profile_id_alter_user_profile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_profile1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='user_profile',
        ),
    ]
